#!/usr/bin/env perl

use Mojolicious::Lite;
use Mojo::ByteStream qw/b/;
use IO::Dir;

my $dir = q[/usr/local/share/pictures/2010-10-30];
app->static->root($dir);
app->types->type(JPG => "image/jpeg");

get '/' => sub {
    my $c = shift;
    tie my %dir, 'IO::Dir', $dir;
    $c->stash(dir => { %dir });
} => 'index';

get '/download/(.file)' => sub {
    my $c = shift;
    my $file = $c->stash("file");
    app->log->debug("serving $file");
    app->static->serve($c,$c->stash("file"));
    $c->rendered;
} => 'download';

get '/thumbnail/(.file)' => sub {
    my $c = shift;
    my $file = $c->stash("file");
    my $tfile = "$dir/thumb_$file";
    unless (-e "$tfile") {
        system("djpeg -scale 1/8 -fast $dir/$file > $tfile")==0
            or app->log->warn("errors scaling: $!");
    }
    app->log->debug("sering thumbnail $tfile");
    app->static->serve($c,"thumb_$file");
    $c->rendered;
} => 'thumb';

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% for my $k (sort keys %$dir) {
% next if $k =~ /^\./;
% next unless $k =~ /jpg$/i;
%= link_to 'download' => {file => $k} => begin
<img src='<%= url_for(thumb => {file => $k})  =%>'><%= $k =%>
%= end
% }

@@ layouts/default.html.ep
<html>
<%= content =%>
</html>

