#!/usr/bin/env perl

use File::Find::Rule;
my $has_jpeg =
  sub { my ( $n, $p, $f ) = @_; @{ [ glob("$f/*.{jpg,JPG}") ] } > 0; };

our @dirs;

@dirs =
  File::Find::Rule->directory->exec($has_jpeg)
  ->in("/home/bduggan/Pictures/share/");

push @dirs,
  File::Find::Rule->directory->exec($has_jpeg)
  ->in("/home/bduggan/Pictures/");

print "$_\n" for sort @dirs;

