#!/usr/bin/env perl

# piccup-send : send files to piccup server

use Mojo::Client;
use Mojo::Transaction::Single;
use File::Basename q/basename/;
use strict;
use warnings;

our $conf = {
    url => q[http://localhost:3000],
    user => "brian",
    pw => "foo"
};

&main;

sub queue_upload {
    my ($client,$file,$failed) = @_;
    my $url =
      Mojo::URL->new( join '/', $conf->{url}, ( basename $file) )
      ->userinfo("$conf->{user}:$conf->{pw}");
    my $contents = Mojo::Asset::File->new( path => $file )->slurp;
    $client->put( $url => { Connection => "Close" },
        $contents => sub { print $file, " : ",$_[0]->res->body, "\n";
            push @$failed, $file unless $_[0]->res->code==200  }
    );
}

sub main {
    my @files = @ARGV;
    if (my @missing = grep {!-e $_} @files) {
        die "Could not open @missing\n";
    }
    my @failed;
    my $client = Mojo::Client->new();
    for my $file (@files) {
        queue_upload($client,$file,\@failed);
    }
    $client->start;
    warn "Failed to upload $_\n" for @failed;
}
