#!/usr/bin/env perl

# qp-send : send files to Quikpic server

use Mojo::Client;
use Mojo::Transaction::Single;
use File::Basename q/basename/;
use strict;
use warnings;

our $conf = {
    url => q[http://localhost:3000],
    user => "brian",
    pw => "foo"
};

&main;

sub main {
    my @files = @ARGV;
    if (my @missing = grep {!-e $_} @files) {
        die "Could not open @missing\n";
    }
    my $client = Mojo::Client->new();
    for my $file (@files) {
        my $url =
          Mojo::URL->new( join '/', $conf->{url}, ( basename $file) )
          ->userinfo("$conf->{user}:$conf->{pw}");
        my $contents = Mojo::Asset::File->new( path => $file )->slurp;
        $client->put( $url => { Connection => "Close" },
            $contents => sub { print $file, " : ",shift->res->body, "\n"; }
        );
    }
    $client->start;
}

