#!/usr/bin/env perl

# qp-send : send files to Quikpic server

use Mojo::Client;
use Mojo::Transaction::Single;
use File::Basename q/basename/;
use strict;
use warnings;

our $conf = {
    url => q[http://localhost:3000],
    user => "brian",
    pw => "foo"
};

&main;

sub main {
    my @files = @ARGV;
    if (my @missing = grep {!-e $_} @files) {
        warn "missing file : $_\n";
    }
    @files = grep { -e $_ } @files;
    my $client = Mojo::Client->new();
    my %results;
    for my $file (@files) {
        my $url = Mojo::URL->new(join '/', $conf->{url}, (basename $file));
        $url->userinfo("$conf->{user}:$conf->{pw}");
        my $tx = $client->build_tx(
            PUT => $url,
            { Connection => "Close" },
            Mojo::Asset::File->new( path => $file )->slurp
        );
        $client->queue($tx);
    }
    $client->start;
}

